### ISSUE TITLE
[Question]:Unable to display images in cool-retro-term terminals

### ISSUE THREAD

**Issue by Yakumo-Yukari** [iinsertNameHere/catnip#87] opened 2024-05-11 10:42 UTC
### Ask your Question:
In kitty terminal, the pictures in the configuration file can be displayed normally, but in cool-retro-term, the pictures will not be displayed, and the pictures can be displayed normally by using viu to output them in the terminal, but they can not be displayed in cool-retro-term when using catnip command.

**Comment by yu-kiat** [comment] 2024-05-12 08:58
The image is shown in cool-retro-term when using the `catnip` command for me.

**Comment by yu-kiat** [comment] 2024-05-13 12:55
Yeah, after further testing, I'm still not able to reproduce this issue.

**Comment by iinsertNameHere** [comment] 2024-05-13 18:33
Yeah, I too can't reproduce... Sorry

**Comment by iinsertNameHere** [comment] 2024-05-14 07:49
Dose viu Work without catnip?

**Comment by iinsertNameHere** [comment] 2024-05-14 20:13
As @yu-kiat and myself can't reproduce the bug, I will close this Issue for now. If you want, you can open a BUG Issue and try to fix it you self.

**Closed** 2024-05-14 20:13 UTC
